config/routes.rb
BookingApp::Application.routes.draw do
  
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

resources :sessions

get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :classrooms

  resources :courses
  resources :events do 
    get 'page/:page', action: :index, on: :collection
  end

  resources :users do
    get 'page/:page', action: :index, on: :collection
  end

  root to: 'sessions#new'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  attr_accessible :name
  has_many :courses
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  # GET /classrooms
  # GET /classrooms.json
   authorize_resource
   def index
    @classrooms = Classroom.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @classrooms }
    end
  end

  # GET /classrooms/1
  # GET /classrooms/1.json
  def show
    @classroom = Classroom.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @classroom }
    end
  end

  # GET /classrooms/new
  # GET /classrooms/new.json
  def new
    @classroom = Classroom.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @classroom }
    end
  end

  # GET /classrooms/1/edit
  def edit
    @classroom = Classroom.find(params[:id])
  end

  # POST /classrooms
  # POST /classrooms.json
  def create
    @classroom = Classroom.new(params[:classroom])

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to @classroom, notice: 'Classroom was successfully created.' }
        format.json { render json: @classroom, status: :created, location: @classroom }
      else
        format.html { render action: "new" }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /classrooms/1
  # PUT /classrooms/1.json
  def update
    @classroom = Classroom.find(params[:id])

    respond_to do |format|
      if @classroom.update_attributes(params[:classroom])
        format.html { redirect_to @classroom, notice: 'Classroom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.json
  def destroy
    @classroom = Classroom.find(params[:id])
    @classroom.destroy

    respond_to do |format|
      format.html { redirect_to classrooms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/_form.html.erb
<%= form_for(@classroom) do |f| %>
  <% if @classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
      <% @classroom.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/classrooms/edit.html.erb
<div class="event">
  <h1>Editing classroom</h1>

<%= render 'form' %>

<%= link_to 'Show', @classroom %> |
<%= link_to 'Back', classrooms_path %>
</div>

app/views/classrooms/edit.html.haml
.event
  %h1 Editing classroom
  = render 'form'
  = link_to 'Show', @classroom
  |
  = link_to 'Back', classrooms_path

app/views/classrooms/index.html.erb
<div class="event">
  <h1>Listing classrooms</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>

<% @classrooms.each do |classroom| %>
  <tr>
    <td><%= classroom.name %></td>
    <td><%= link_to 'Show', classroom %></td>
    <% if can? :update, classroom %>
    <td><%= link_to 'Edit', edit_classroom_path(classroom) %></td>
    <td><%= link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
    <%end%>
<% end %>
</table>

<br />
</div>

app/views/classrooms/index.html.haml
.event
  %h1 Listing classrooms
  %table
    %tr
      %th Name
    - @classrooms.each do |classroom|
      %tr
        %td= classroom.name
        %td= link_to 'Show', classroom
        - if can? :update, classroom
          %td= link_to 'Edit', edit_classroom_path(classroom)
          %td= link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' }
  %br/

app/views/classrooms/new.html.erb
<div class="event">
  <h1>New classroom</h1>

<%= render 'form' %>

<%= link_to 'Back', classrooms_path %>
</div>

app/views/classrooms/new.html.haml
.event
  %h1 New Classroom
  = render 'form'
  = link_to 'Back', classrooms_path

app/views/classrooms/old_edit.html.erb
<div class="event">
  <h1>Editing classroom</h1>

<%= render 'form' %>

<%= link_to 'Show', @classroom %> |
<%= link_to 'Back', classrooms_path %>
</div>

app/views/classrooms/old_form.html.erb
<%= form_for(@classroom) do |f| %>
  <% if @classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
      <% @classroom.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/classrooms/old_index.html.erb
<div class="event">
  <h1>Listing classrooms</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>

<% @classrooms.each do |classroom| %>
  <tr>
    <td><%= classroom.name %></td>
    <td><%= link_to 'Show', classroom %></td>
    <% if can? :update, classroom %>
    <td><%= link_to 'Edit', edit_classroom_path(classroom) %></td>
    <td><%= link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
    <%end%>
<% end %>
</table>

<br />
</div>

app/views/classrooms/old_new.html.erb
<div class="event">
  <h1>New classroom</h1>

<%= render 'form' %>

<%= link_to 'Back', classrooms_path %>
</div>

app/views/classrooms/old_show.html.erb
<div class="event">
  <p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @classroom.name %>
</p>

<%if can? :update, Classroom %>
<%= link_to 'Edit', edit_classroom_path(@classroom) %> 
<%end%>
<%= link_to 'Back', classrooms_path %>
</div>

app/views/classrooms/show.html.erb
<div class="event">
  <p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @classroom.name %>
</p>

<%if can? :update, Classroom %>
<%= link_to 'Edit', edit_classroom_path(@classroom) %> 
<%end%>
<%= link_to 'Back', classrooms_path %>
</div>

app/views/classrooms/show.html.haml
.event
  %p#notice= notice
  %p
    %b Name:
    = @classroom.name
  - if can? :update, Classroom
    = link_to 'Edit', edit_classroom_path(@classroom)
  = link_to 'Back', classrooms_path

  