config/routes.rb
BookingApp::Application.routes.draw do
  
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

resources :sessions

get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :classrooms

  resources :courses
  resources :events do 
    get 'page/:page', action: :index, on: :collection
  end

  resources :users do
    get 'page/:page', action: :index, on: :collection
  end

  root to: 'sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :description, :email, :image, :name, :password, :password_confirmation, :username, :course_ids, :role, :event_ids, :user_image, :remote_user_image_url
  mount_uploader :user_image, UserImageUploader
  has_and_belongs_to_many :events

  has_secure_password

  validates :password, presence: true, on: :create
  validates :email, presence: true
  validates :email, uniqueness: { case_sensitive: false}
  
  before_save :ensure_role_is_set

  def ensure_role_is_set
    self.role = :student if self.role.nil?
  end

  def role?(role_to_compare)
  self.role.to_s == role_to_compare.to_s
 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  authorize_resource
  def index
    @q = User.order(:created_at).page(params[:page]).search(params[:q])
    
    @users = @q.result(distinct: true)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
 
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field_description">
    <%= f.label :description %><br />
    <%= f.text_area :description, size: "20x5" %>
  </div>
   <div class="field">
    <%= f.label :user_image %><br />
    <%= f.file_field :user_image %><br />
   
    <%= f.text_field :remote_user_image_url %> 
    <%= f.label :remote_user_image_url %>
  </div>
  
<%if can? :update, User%>
  <div class="field">
    <%= f.label :Pick_a_role_ninja_instructor_or_student %><br />
    <%= f.text_field :role %>
  </div>
  <%end%>

  <div class="field">
  <%= f.label :Pick_a_course_that_you_are_teaching %><br />
    <%Event.all.each do |event|  %>
      <%= check_box_tag "user[event_ids][]", event.id, @user.event_ids.include?(event.id) %>
      <%= event.name %><br />
      Starting on: <%= event.start_at %><br />
      Finishing on: <%= event.end_at %><br />
    <% end %>
  </div>


  <div class="actions">
    <%= f.submit 'Create profile'%>
  </div>
<% end %>

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :username
    %br/
    = f.text_field :username
  .field_description
    = f.label :description
    %br/
    = f.text_area :description, size: "20x5"
  .field
    = f.label :user_image
    %br/
    = f.file_field :user_image
    %br/
    = f.text_field :remote_user_image_url
    = f.label :remote_user_image_url
  - if can? :update, User
    .field
      = f.label :Pick_a_role_ninja_instructor_or_student
      %br/
      = f.text_field :role
  .field
    = f.label :Pick_a_course_that_you_are_teaching
    %br/
    - Event.all.each do |event|
      = check_box_tag "user[event_ids][]", event.id, @user.event_ids.include?(event.id)
      = event.name
      %br/
      Starting on: #{event.start_at}
      %br/
      Finishing on: #{event.end_at}
      %br/
  .actions
    = f.submit 'Create profile'

app/views/users/edit.html.erb
<div class="event">
<h1>Editing user</h1>

<%= render 'form' %>


<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
</end>

app/views/users/edit.html.haml
.event
  %h1 Editing User 
  = render 'form'
  = link_to 'Show', @user
  = link_to 'Back', users_path

app/views/users/index.html.erb
<div class="event">
  <h1>Profiles</h1>
<%= search_form_for @q do |f| %>

<p>
  <%=f.label 'People Finder'%>
  <%= f.text_field :name_cont %>
</p>
<p>
  <%=f.submit%>
</p>
<%end %>

<table>
  <tr>
    <th>Name</th>
    <th>Role</th>
  </tr>

  <% @users.each do |user| %>
  <tr>
    <td><%= link_to user.name, user %><br /><div class="profpic">
      <%= link_to image_tag(user.user_image.thumb.url), user%></div><br /> <br />
  </td>
    
    <td><%= user.role %></td>
    <% if can? :update, user %>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  <% end %>
</table>

<br />
<%= paginate @users, theme: 'twitter-bootstrap'%>
</div>

app/views/users/index.html.haml
.event
  %h1 Profiles
  = search_form_for @q do |f|
    %p
      = f.label 'People Finder'
      = f.text_field :name_cont
    %p
      = f.submit
  %table
    %tr
      %th Name
      %th Role
    - @users.each do |user|
      %tr
        %td
          = link_to user.name, user
          %br/
          .profpic
            = link_to image_tag(user.user_image.thumb.url), user
          %br/
          %br/
        %td= user.role
        - if can? :update, user
          %td= link_to 'Edit', edit_user_path(user)
          %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  = paginate @users, theme: 'twitter-bootstrap'

app/views/users/new.html.erb
<div class="sign_up">
<h1>Sign Up</h1>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field_description">
    <%= f.label :description %><br />
    <%= f.text_area :description, size: "20x5" %>
  </div>
     <div class="field">
    <%= f.label :user_image %><br />
    <%= f.file_field :user_image %><br />
    <%= f.label :remote_user_image_url %><br />
    <%= f.text_field :remote_user_image_url %>
  </div>
    <div class="actions"><%= f.submit %></div>
  <% end %>

<%= link_to 'Back', users_path %>
</div>

app/views/users/old_edit.html.erb
<div class="event">
<h1>Editing user</h1>

<%= render 'form' %>


<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
</end>

app/views/users/old_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
 
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field_description">
    <%= f.label :description %><br />
    <%= f.text_area :description, size: "20x5" %>
  </div>
   <div class="field">
    <%= f.label :user_image %><br />
    <%= f.file_field :user_image %><br />
   
    <%= f.text_field :remote_user_image_url %> 
    <%= f.label :remote_user_image_url %>
  </div>
  
<%if can? :update, User%>
  <div class="field">
    <%= f.label :Pick_a_role_ninja_instructor_or_student %><br />
    <%= f.text_field :role %>
  </div>
  <%end%>

  <div class="field">
  <%= f.label :Pick_a_course_that_you_are_teaching %><br />
    <%Event.all.each do |event|  %>
      <%= check_box_tag "user[event_ids][]", event.id, @user.event_ids.include?(event.id) %>
      <%= event.name %><br />
      Starting on: <%= event.start_at %><br />
      Finishing on: <%= event.end_at %><br />
    <% end %>
  </div>


  <div class="actions">
    <%= f.submit 'Create profile'%>
  </div>
<% end %>

app/views/users/old_index.html.erb
<div class="event">
  <h1>Profiles</h1>
<%= search_form_for @q do |f| %>

<p>
  <%=f.label 'People Finder'%>
  <%= f.text_field :name_cont %>
</p>
<p>
  <%=f.submit%>
</p>
<%end %>

<table>
  <tr>
    <th>Name</th>
    <th>Role</th>
  </tr>

  <% @users.each do |user| %>
  <tr>
    <td><%= link_to user.name, user %><br /><div class="profpic">
      <%= link_to image_tag(user.user_image.thumb.url), user%></div><br /> <br />
  </td>
    
    <td><%= user.role %></td>
    <% if can? :update, user %>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  <% end %>
</table>

<br />
<%= paginate @users, theme: 'twitter-bootstrap'%>
</div>

app/views/users/old_show.html.erb
<div class="event">
  <p id="notice"><%= notice %></p>
  <p>
   <b> <%= @user.username %></b>
  </p>
<div class="profile_image">
<%= image_tag @user.user_image.profile.url%>
</div>
<br />
<br />
<div class='profile'>
  <p>
    <b>Full Name:</b><br />
    <%= @user.name %>
  </p>

  <p>
  <b>Email:</b><br />
  <%= @user.email %>
</p>




<p>
  <b>Role:</b></br>
  <%= @user.role %>
</p>
</div>
<div class="description">
<p>
  <b>Description:</b>
  <%= @user.description %>
</p>


<p>

<b>Courses: </b>
    <%@user.events.each do |event|%>
 <li><%=link_to "#{event.name}", event_path %></li>
  <%end%>
</p>
</div>
<div class="edit_buttons">
<%if can? :create, User%>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%end%>
<%= link_to 'Back', users_path %>
</div>
</div>

app/views/users/show.html.erb
<div class="event">
  <p id="notice"><%= notice %></p>
  <p>
   <b> <%= @user.username %></b>
  </p>
<div class="profile_image">
<%= image_tag @user.user_image.profile.url%>
</div>
<br />
<br />
<div class='profile'>
  <p>
    <b>Full Name:</b><br />
    <%= @user.name %>
  </p>

  <p>
  <b>Email:</b><br />
  <%= @user.email %>
</p>




<p>
  <b>Role:</b></br>
  <%= @user.role %>
</p>
</div>
<div class="description">
<p>
  <b>Description:</b>
  <%= @user.description %>
</p>


<p>

<b>Courses: </b>
    <%@user.events.each do |event|%>
 <li><%=link_to "#{event.name}", event_path %></li>
  <%end%>
</p>
</div>
<div class="edit_buttons">
<%if can? :create, User%>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%end%>
<%= link_to 'Back', users_path %>
</div>
</div>

app/views/users/show.html.haml
.event
  %p#notice= notice
  %p
    %b
      = @user.username
  .profile_image
    = image_tag @user.user_image.profile.url
  %br/
  %br/
  .profile
    %p
      %b Full Name:
      %br/
      = @user.name
    %p
      %b Email:
      %br/
      = @user.email
    %p
      %b Role:
      = @user.role
  .description
    %p
      %b Description:
      = @user.description
    %p
      %b Courses:
      - @user.events.each do |event|
        %li= link_to "#{event.name}", event_path
  .edit_buttons
    - if can? :create, User
      = link_to 'Edit', edit_user_path(@user)
      |
    = link_to 'Back', users_path