config/routes.rb
BookingApp::Application.routes.draw do
  
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

resources :sessions

get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :classrooms

  resources :courses
  resources :events do 
    get 'page/:page', action: :index, on: :collection
  end

  resources :users do
    get 'page/:page', action: :index, on: :collection
  end

  root to: 'sessions#new'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :name, :start_at, :end_at, :description, :length, :user_ids, :classroom_id, :student_ids, :instructor_ids
  has_event_calendar

  has_and_belongs_to_many :students, class_name: "User", conditions: ["role=?", "student"]

  has_and_belongs_to_many :instructors, class_name: "User", conditions: ["role=?", "instructor"]
  belongs_to :classroom
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  authorize_resource
  def index
    @q = Event.order(:created_at).page(params[:page]).search(params[:q])
    @events = @q.result(distinct: true)
    @q.build_condition
    # @events = Event.order(:created_at).page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
    calendar_params

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])
    # @event = current_user.events.new(params[:event]) 
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
    <div class="field_description">
    <%= f.label :description %><br />
    <%= f.text_area :description, size: "20x5" %>
  </div>
  <div class="field">
    <%= f.label :start_at %><br />
    <%= f.date_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :end_at %><br />
    <%= f.date_select :end_at %>
  </div>
  <%= f.label :pick_classroom%>
   <%= f.collection_select(:classroom_id, Classroom.all, :id, :name, prompt: true)%>
 
    <div class="field_student">
  <%= f.label 'assign_a_student:' %>
    <%User.where(role: 'student').each do |student|  %>
      <%= check_box_tag "event[student_ids][]", student.id, @event.student_ids.include?(student.id) %>
      <%= student.name %>
    <% end %>
  </div>
  <div class="field_instructor">
  <%= f.label 'assign_a_instructor:' %>
    <%User.where(role: 'instructor').each do |instructor|  %>
      <%= check_box_tag "event[instructor_ids][]", instructor.id, @event.instructor_ids.include?(instructor.id) %>
      <%= instructor.name %>
    <% end %>
  </div>
   <div class="actions">
    <%= f.submit 'Create course' %>
  </div>
<% end %>

app/views/events/_form.html.haml
= form_for(@event) do |f|
  - if @event.errors.any?
    #error_explanation
      %h2
        = pluralize(@event.errors.count, "error")
        prohibited this event from being saved:
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field_description
    = f.label :description
    %br/
    = f.text_area :description, size: "20x5"
  .field
    = f.label :start_at
    %br/
    = f.date_select :start_at
  .field
    = f.label :end_at
    %br/
    = f.date_select :end_at
  = f.label :pick_classroom
  = f.collection_select(:classroom_id, Classroom.all, :id, :name, prompt: true)
  .field_student
    = f.label 'assign_a_student:'
    - User.where(role: 'student').each do |student|
      = check_box_tag "event[student_ids][]", student.id, @event.student_ids.include?(student.id)
      = student.name
  .field_instructor
    = f.label 'assign_a_instructor:'
    - User.where(role: 'instructor').each do |instructor|
      = check_box_tag "event[instructor_ids][]", instructor.id, @event.instructor_ids.include?(instructor.id)
      = instructor.name
  .actions
    = f.submit 'Create course'

app/views/events/edit.html.erb
<div class="event">
  <h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>
</div>

app/views/events/edit.html.haml
.event
  %h1 New course
  = render 'form'
  = raw(event_calendar)
  = link_to 'Back', events_path

app/views/events/index.html.erb
<div class="event">

    <h1>Listing courses</h1>
<%=search_form_for @q do |f|%>
<%= f.condition_fields do |c|%>
    <div>
        <%= c.attribute_fields do |a|%>
            <%= a.attribute_select associations: [:user]%>
        <%end%>
        <%= c.predicate_select%>
            <%= c.value_fields do |v|%>
                <%= v.text_field :value %>
            <%end%>
    </div>
        <%end%>
    <%=f.submit%>
<%end%>
<table>
  <tr>
    <th>Name</th>
    <th>Start at</th>
    <th>End at</th>
    <th>Classroom</th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.start_at %></td>
    <td><%= event.end_at %></td>
    <td><%= event.classroom_id %></td>
    <td><%= link_to 'Show', event %></td>
    <% event.instructor_ids.each do |i| %>
    <% if i == current_user.id %>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <%end%>
    <%end%>
<% end %>
</table>
<br />

 <%= paginate @events, theme: 'twitter-bootstrap'%> 
</div>

app/views/events/index.html.haml
.event
  %h1 Listing courses
  = search_form_for @q do |f|
    = f.condition_fields do |c|
      %div
        = c.attribute_fields do |a|
          = a.attribute_select associations: [:user]
        = c.predicate_select
        = c.value_fields do |v|
          = v.text_field :value
    = f.submit
  %table
    %tr
      %th Name
      %th Start at
      %th End at
      %th Classroom
      %th
    - @events.each do |event|
      %tr
        %td= event.name
        %td= event.start_at
        %td= event.end_at
        %td= event.classroom_id
        %td= link_to 'Show', event
        - event.instructor_ids.each do |i|
          - if i == current_user.id
            %td= link_to 'Edit', edit_event_path(event)
            %td= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  = paginate @events, theme: 'twitter-bootstrap'

app/views/events/new.html.erb
<div class="event">
  <h1>New course</h1>

<%= render 'form' %>
<%= raw(event_calendar) %>
<%= link_to 'Back', events_path %>
</div>

app/views/events/old_edit.html.erb
<div class="event">
  <h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>
</div>

app/views/events/old_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
    <div class="field_description">
    <%= f.label :description %><br />
    <%= f.text_area :description, size: "20x5" %>
  </div>
  <div class="field">
    <%= f.label :start_at %><br />
    <%= f.date_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :end_at %><br />
    <%= f.date_select :end_at %>
  </div>
  <%= f.label :pick_classroom%>
   <%= f.collection_select(:classroom_id, Classroom.all, :id, :name, prompt: true)%>
 
    <div class="field_student">
  <%= f.label 'assign_a_student:' %>
    <%User.where(role: 'student').each do |student|  %>
      <%= check_box_tag "event[student_ids][]", student.id, @event.student_ids.include?(student.id) %>
      <%= student.name %>
    <% end %>
  </div>
  <div class="field_instructor">
  <%= f.label 'assign_a_instructor:' %>
    <%User.where(role: 'instructor').each do |instructor|  %>
      <%= check_box_tag "event[instructor_ids][]", instructor.id, @event.instructor_ids.include?(instructor.id) %>
      <%= instructor.name %>
    <% end %>
  </div>
   <div class="actions">
    <%= f.submit 'Create course' %>
  </div>
<% end %>

app/views/events/old_index.html.erb
<div class="event">

    <h1>Listing courses</h1>
<%=search_form_for @q do |f|%>
<%= f.condition_fields do |c|%>
    <div>
        <%= c.attribute_fields do |a|%>
            <%= a.attribute_select associations: [:user]%>
        <%end%>
        <%= c.predicate_select%>
            <%= c.value_fields do |v|%>
                <%= v.text_field :value %>
            <%end%>
    </div>
        <%end%>
    <%=f.submit%>
<%end%>
<table>
  <tr>
    <th>Name</th>
    <th>Start at</th>
    <th>End at</th>
    <th>Classroom</th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.start_at %></td>
    <td><%= event.end_at %></td>
    <td><%= event.classroom_id %></td>
    <td><%= link_to 'Show', event %></td>
    <% event.instructor_ids.each do |i| %>
    <% if i == current_user.id %>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <%end%>
    <%end%>
<% end %>
</table>
<br />

 <%= paginate @events, theme: 'twitter-bootstrap'%> 
</div>

app/views/events/old_new.html.erb
<div class="event">
  <h1>New course</h1>

<%= render 'form' %>
<%= raw(event_calendar) %>
<%= link_to 'Back', events_path %>
</div>

app/views/events/old_show.html.erb
<div class="event">
  <p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Start at:</b>
  <%= @event.start_at %>
</p>

<p>
  <b>End at:</b>
  <%= @event.end_at %>
</p>
<p>
  <b>End at:</b>
  <%= @event.description %>
</p>
<p>
<b>Instructors: </b>
    <%@event.instructors.each do |instructor|%>
 <li><%=link_to "#{instructor.name}", user_path %></li>
  <%end%>
</p>
<p>
<b>Students: </b>
    <%@event.students.each do |student|%>
 <li><%=link_to "#{student.name}", user_path %></li>
  <%end%>
</p>
<%if can? :update, Event%>
<%= link_to 'Edit', edit_event_path(@event) %> |
<%end%>
<%= link_to 'Back', events_path %>
</div>

app/views/events/show.html.erb
<div class="event">
  <p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Start at:</b>
  <%= @event.start_at %>
</p>

<p>
  <b>End at:</b>
  <%= @event.end_at %>
</p>
<p>
  <b>End at:</b>
  <%= @event.description %>
</p>
<p>
<b>Instructors: </b>
    <%@event.instructors.each do |instructor|%>
 <li><%=link_to "#{instructor.name}", user_path %></li>
  <%end%>
</p>
<p>
<b>Students: </b>
    <%@event.students.each do |student|%>
 <li><%=link_to "#{student.name}", user_path %></li>
  <%end%>
</p>
<%if can? :update, Event%>
<%= link_to 'Edit', edit_event_path(@event) %> |
<%end%>
<%= link_to 'Back', events_path %>
</div>

app/views/events/show.html.haml
.event 
  %h1 New Course
  = render 'form'
  = raw(event_calendar)
  = link_to 'Back', events_path
  