config/routes.rb
BookingApp::Application.routes.draw do
  
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

resources :sessions

get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :classrooms

  resources :courses
  resources :events do 
    get 'page/:page', action: :index, on: :collection
  end

  resources :users do
    get 'page/:page', action: :index, on: :collection
  end

  root to: 'sessions#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lulu Booking</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <div class="sessions">
      <% flash.each do |name, msg| %>
      <div class="flash-message"<%= name %>">
        <%= msg %>
      </div>
      <% end %>
      <%if current_user %>
      hello <%= current_user.username%> (<%= current_user.role%>)
      <%=link_to "logout", logout_path%>
      <%else%>
      <%=link_to "login", new_session_path%> or <%=link_to "signup", new_user_path%>
      <%end%>
      <div class="imagebanner">
        <%= image_tag("https://lh5.ggpht.com/KWwubVUG6SBHp5ypw3oCX0ACFND9S9ZX3BFQvBCYVgEqvrg_nNz03sQVoSbG9S6S8ww=w300", :alt => "scheduler") %>
        <h2><span>Lulu Booking</span></h2>
      </div>
    </div>
    <div class="topnavbar">
      <nav>
        <%= link_to('Classrooms', classrooms_path) %>
        <%= link_to('Courses', events_path) %>
        <%= link_to('Profiles', users_path) %>
        <%= link_to('Calendar', calendar_path) %>
      </nav>
    </div>
  </div>
  <%if current_user%>
  <%if current_user.role != "student"%>
  <div class ="sidenavbar">
    <nav>
      <ul>
        <li>
          <div class="nav"><%= link_to('Create Classroom', new_classroom_path) %></div></li>
        <li><div class="nav"><%= link_to('Create Course', new_event_path) %></div></li>
        <li><div class="nav"><%= link_to('Create Profile', new_user_path) %></div></li>
      </ul>
    </nav>
  </div>
  <%else%>
  <div class="sidenavbar">
   </div>
  <%end%>
  <%else%>
  <div class="sidenavbar">
   </div>
  <%end%>
  <div class="containerapp">
    <%= yield %>
  </div>
  <div class="footer">
    <div class="footermenu">
      <table>
        <tbody>
          <tr>
            <th colspan = "2">Lulu Booking </th>
            <th colspan="2">Popular Courses</th>
            <th>Other Information</th>
          </tr>
          <tr>
            <td align ='left'>
              Unit 1 (Ground Floor) <br>
              London House <br>
              London E15 1NY<br>
              United Kingdom<br>
              Tel:+44 (0)208 123 4567<br>
              Email:<%= link_to "lulubooking@booking.com", "http://www.google.com" %>
            </td>
            <td>
            </td>
            <td>
              <ol>
                <li><%= link_to "WDI-1", "http://www.google.com" %></li>
                <li><%= link_to "WDI-2", "http://www.google.com" %></li>
                <li><%= link_to "WDI-3", "http://www.google.com" %></li>
                <li><%= link_to "WDI-4", "http://www.google.com" %></li>
              </ol>
            </td>
            <td>
              <ol>
                <li><%= link_to "WDI-5", "http://www.google.com" %></li>
                <li><%= link_to "WDI-6", "http://www.google.com" %></li>
                <li><%= link_to "WDI-7", "http://www.google.com"%></li>
                <li><%= link_to "WDI-7", "http://www.google.com"%></li>
              </ol>
            </td>
            <td>
              <ol>
                <li><%= link_to "About us", "http://www.google.com" %></li>
                <li><%= link_to "Contact", "http://www.google.com" %></li>
                <li><%= link_to "About us", "http://www.google.com" %></li>
                <li><%= link_to "About us", "http://www.google.com" %></li>
              </ol>
            </td>
          </tr>
        </tbody>
      </table>

    </div>
    <footer>Lulu Copyright 2014</footer>
  </div>
</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Lulu Booking
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    %link{:href => "https://fonts.googleapis.com/css?family=Indie+Flower", :rel => "stylesheet", :type => "text/css"}
      %link{:href => "https://fonts.googleapis.com/css?family=Droid+Sans:400,700", :rel => "stylesheet", :type => "text/css"}
        = csrf_meta_tags
  %body
    .header
      .sessions
        - flash.each do |name, msg|
          <div class="flash-message"#{name}">
          \#{msg}
      - if current_user
        hello #{current_user.username} (#{current_user.role})
        \#{link_to "logout", logout_path}
      - else
        = link_to "login", new_session_path
        or #{link_to "signup", new_user_path}
      .imagebanner
        = image_tag("https://lh5.ggpht.com/KWwubVUG6SBHp5ypw3oCX0ACFND9S9ZX3BFQvBCYVgEqvrg_nNz03sQVoSbG9S6S8ww=w300", :alt => "scheduler")
        %h2
          %span Lulu Booking
    .topnavbar
      %nav
        = link_to('Classrooms', classrooms_path)
        = link_to('Courses', events_path)
        = link_to('Profiles', users_path)
        = link_to('Calendar', calendar_path)
    - if current_user
      - if current_user.role != "student"
        .sidenavbar
          %nav
            %ul
              %li
                .nav= link_to('Create Classroom', new_classroom_path)
              %li
                .nav= link_to('Create Course', new_event_path)
              %li
                .nav= link_to('Create Profile', new_user_path)
      - else
        .sidenavbar
    - else
      .sidenavbar
    .containerapp
      = yield
    .footer
      .footermenu
        %table
          %tbody
            %tr
              %th{:colspan => "2"} Lulu Booking
              %th{:colspan => "2"} Popular Courses
              %th Other Information
            %tr
              %td{:align => "left"}
                Unit 1 (Ground Floor)
                %br
                  London House
                  %br
                    London E15 1NY
                    %br
                      United Kingdom
                      %br
                        Tel:+44 (0)208 123 4567
                        %br
                          Email:#{link_to "lulubooking@booking.com", "http://www.google.com"}
              %td
              %td
                %ol
                  %li= link_to "WDI-1", "http://www.google.com"
                  %li= link_to "WDI-2", "http://www.google.com"
                  %li= link_to "WDI-3", "http://www.google.com"
                  %li= link_to "WDI-4", "http://www.google.com"
              %td
                %ol
                  %li= link_to "WDI-5", "http://www.google.com"
                  %li= link_to "WDI-6", "http://www.google.com"
                  %li= link_to "WDI-7", "http://www.google.com"
                  %li= link_to "WDI-7", "http://www.google.com"
              %td
                %ol
                  %li= link_to "About us", "http://www.google.com"
                  %li= link_to "Contact", "http://www.google.com"
                  %li= link_to "About us", "http://www.google.com"
                  %li= link_to "About us", "http://www.google.com"
      %footer Lulu Copyright 2014

app/views/layouts/old_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lulu Booking</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <div class="sessions">
      <% flash.each do |name, msg| %>
      <div class="flash-message"<%= name %>">
        <%= msg %>
      </div>
      <% end %>
      <%if current_user %>
      hello <%= current_user.username%> (<%= current_user.role%>)
      <%=link_to "logout", logout_path%>
      <%else%>
      <%=link_to "login", new_session_path%> or <%=link_to "signup", new_user_path%>
      <%end%>
      <div class="imagebanner">
        <%= image_tag("https://lh5.ggpht.com/KWwubVUG6SBHp5ypw3oCX0ACFND9S9ZX3BFQvBCYVgEqvrg_nNz03sQVoSbG9S6S8ww=w300", :alt => "scheduler") %>
        <h2><span>Lulu Booking</span></h2>
      </div>
    </div>
    <div class="topnavbar">
      <nav>
        <%= link_to('Classrooms', classrooms_path) %>
        <%= link_to('Courses', events_path) %>
        <%= link_to('Profiles', users_path) %>
        <%= link_to('Calendar', calendar_path) %>
      </nav>
    </div>
  </div>
  <%if current_user%>
  <%if current_user.role != "student"%>
  <div class ="sidenavbar">
    <nav>
      <ul>
        <li>
          <div class="nav"><%= link_to('Create Classroom', new_classroom_path) %></div></li>
        <li><div class="nav"><%= link_to('Create Course', new_event_path) %></div></li>
        <li><div class="nav"><%= link_to('Create Profile', new_user_path) %></div></li>
      </ul>
    </nav>
  </div>
  <%else%>
  <div class="sidenavbar">
   </div>
  <%end%>
  <%else%>
  <div class="sidenavbar">
   </div>
  <%end%>
  <div class="containerapp">
    <%= yield %>
  </div>
  <div class="footer">
    <div class="footermenu">
      <table>
        <tbody>
          <tr>
            <th colspan = "2">Lulu Booking </th>
            <th colspan="2">Popular Courses</th>
            <th>Other Information</th>
          </tr>
          <tr>
            <td align ='left'>
              Unit 1 (Ground Floor) <br>
              London House <br>
              London E15 1NY<br>
              United Kingdom<br>
              Tel:+44 (0)208 123 4567<br>
              Email:<%= link_to "lulubooking@booking.com", "http://www.google.com" %>
            </td>
            <td>
            </td>
            <td>
              <ol>
                <li><%= link_to "WDI-1", "http://www.google.com" %></li>
                <li><%= link_to "WDI-2", "http://www.google.com" %></li>
                <li><%= link_to "WDI-3", "http://www.google.com" %></li>
                <li><%= link_to "WDI-4", "http://www.google.com" %></li>
              </ol>
            </td>
            <td>
              <ol>
                <li><%= link_to "WDI-5", "http://www.google.com" %></li>
                <li><%= link_to "WDI-6", "http://www.google.com" %></li>
                <li><%= link_to "WDI-7", "http://www.google.com"%></li>
                <li><%= link_to "WDI-7", "http://www.google.com"%></li>
              </ol>
            </td>
            <td>
              <ol>
                <li><%= link_to "About us", "http://www.google.com" %></li>
                <li><%= link_to "Contact", "http://www.google.com" %></li>
                <li><%= link_to "About us", "http://www.google.com" %></li>
                <li><%= link_to "About us", "http://www.google.com" %></li>
              </ol>
            </td>
          </tr>
        </tbody>
      </table>

    </div>
    <footer>Lulu Copyright 2014</footer>
  </div>
</body>
</html>

app/views/layouts/old_application.html.haml
!!!
%html
  %head
    %title Lulu Booking
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    %link{:href => "https://fonts.googleapis.com/css?family=Indie+Flower", :rel => "stylesheet", :type => "text/css"}
      %link{:href => "https://fonts.googleapis.com/css?family=Droid+Sans:400,700", :rel => "stylesheet", :type => "text/css"}
        = csrf_meta_tags
  %body
    .header
      .sessions
        - flash.each do |name, msg|
          <div class="flash-message"#{name}">
          \#{msg}
      - if current_user
        hello #{current_user.username} (#{current_user.role})
        \#{link_to "logout", logout_path}
      - else
        = link_to "login", new_session_path
        or #{link_to "signup", new_user_path}
      .imagebanner
        = image_tag("https://lh5.ggpht.com/KWwubVUG6SBHp5ypw3oCX0ACFND9S9ZX3BFQvBCYVgEqvrg_nNz03sQVoSbG9S6S8ww=w300", :alt => "scheduler")
        %h2
          %span Lulu Booking
    .topnavbar
      %nav
        = link_to('Classrooms', classrooms_path)
        = link_to('Courses', events_path)
        = link_to('Profiles', users_path)
        = link_to('Calendar', calendar_path)
    - if current_user
      - if current_user.role != "student"
        .sidenavbar
          %nav
            %ul
              %li
                .nav= link_to('Create Classroom', new_classroom_path)
              %li
                .nav= link_to('Create Course', new_event_path)
              %li
                .nav= link_to('Create Profile', new_user_path)
      - else
        .sidenavbar
    - else
      .sidenavbar
    .containerapp
      = yield
    .footer
      .footermenu
        %table
          %tbody
            %tr
              %th{:colspan => "2"} Lulu Booking
              %th{:colspan => "2"} Popular Courses
              %th Other Information
            %tr
              %td{:align => "left"}
                Unit 1 (Ground Floor)
                %br
                  London House
                  %br
                    London E15 1NY
                    %br
                      United Kingdom
                      %br
                        Tel:+44 (0)208 123 4567
                        %br
                          Email:#{link_to "lulubooking@booking.com", "http://www.google.com"}
              %td
              %td
                %ol
                  %li= link_to "WDI-1", "http://www.google.com"
                  %li= link_to "WDI-2", "http://www.google.com"
                  %li= link_to "WDI-3", "http://www.google.com"
                  %li= link_to "WDI-4", "http://www.google.com"
              %td
                %ol
                  %li= link_to "WDI-5", "http://www.google.com"
                  %li= link_to "WDI-6", "http://www.google.com"
                  %li= link_to "WDI-7", "http://www.google.com"
                  %li= link_to "WDI-7", "http://www.google.com"
              %td
                %ol
                  %li= link_to "About us", "http://www.google.com"
                  %li= link_to "Contact", "http://www.google.com"
                  %li= link_to "About us", "http://www.google.com"
                  %li= link_to "About us", "http://www.google.com"
      %footer Lulu Copyright 2014